1. numpy
2. pandas
3. 머신러닝(신경망x)
4. 딥러닝(신경망)
  
gole : 딥러닝의 코드 이해. 적용할수 있다.

# numpy
- 산술연산을 위한 패키지
    - ndarray (다차원 배열) 배열 연산 + 브로드캐스팅 기능을 이용해 연산 가능하게 해준다.
    - 장점 : 반복문을 작성할 필요가 없다.
    - 선형대수, 난수 생성
- numpy 산술데이터 처리만 가능한 라이브러리, pandas 통계 분석 처리를 위한 라이브러리


In [9]:
import numpy as np

In [10]:
my_arr = np.arange(1000)

In [11]:
my_arr?

In [7]:
my_list_1 = [i for i in range(1000)]

In [12]:
my_list_1?

- 리스트 : 객체 저장소

In [35]:
list_2 = [print, range]

In [36]:
list_2 * 2

[<function print>, range, <function print>, range]

In [37]:
list_2[0]("hello world")

hello world


In [38]:
list_2[1](10)

range(0, 10)

In [39]:
type(my_list_1)

list

In [40]:
my_array_1 = np.array(my_list_1)

In [41]:
my_array_1 *2

array([   0,    2,    4,    6,    8,   10,   12,   14,   16,   18,   20,
         22,   24,   26,   28,   30,   32,   34,   36,   38,   40,   42,
         44,   46,   48,   50,   52,   54,   56,   58,   60,   62,   64,
         66,   68,   70,   72,   74,   76,   78,   80,   82,   84,   86,
         88,   90,   92,   94,   96,   98,  100,  102,  104,  106,  108,
        110,  112,  114,  116,  118,  120,  122,  124,  126,  128,  130,
        132,  134,  136,  138,  140,  142,  144,  146,  148,  150,  152,
        154,  156,  158,  160,  162,  164,  166,  168,  170,  172,  174,
        176,  178,  180,  182,  184,  186,  188,  190,  192,  194,  196,
        198,  200,  202,  204,  206,  208,  210,  212,  214,  216,  218,
        220,  222,  224,  226,  228,  230,  232,  234,  236,  238,  240,
        242,  244,  246,  248,  250,  252,  254,  256,  258,  260,  262,
        264,  266,  268,  270,  272,  274,  276,  278,  280,  282,  284,
        286,  288,  290,  292,  294,  296,  298,  3

In [42]:
my_arr2=np.array(list_2)

In [43]:
my_arr2[0]("hello world")

hello world


In [44]:
type(my_arr2)

numpy.ndarray

In [45]:
my_list_1 * 2

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,


In [46]:
my_arr = np.arange(100000)

In [47]:
%time for _ in range(10):my_arr2 = my_arr*2

Wall time: 1e+03 µs


In [48]:
my_arr2

array([     0,      2,      4, ..., 199994, 199996, 199998])

In [49]:
my_list = list(my_arr)

In [50]:
%time for _ in range(10):my_list2 = [i*2 for i in my_list ]

Wall time: 398 ms


Numpy ndarray : 다차원 배열 객체
- numpy 는 ndarray라고 하는 N차원 배열 객체 사용

In [51]:
data = np.random.randn(2,3)

In [52]:
data

array([[ 0.92230624, -1.51439758,  1.58033582],
       [-0.34252766, -1.10818752, -0.57169977]])

In [53]:
data.shape

(2, 3)

In [54]:
data *10

array([[  9.22306243, -15.14397585,  15.80335821],
       [ -3.42527657, -11.08187518,  -5.71699768]])

In [55]:
data + data

array([[ 1.84461249, -3.02879517,  3.16067164],
       [-0.68505531, -2.21637504, -1.14339954]])

# ndarray 생성

In [56]:
data1 = np.random.randn(3,3)

In [57]:
data2 = np.random.randn(2,3)

In [58]:
data1 + data2

ValueError: operands could not be broadcast together with shapes (3,3) (2,3) 

In [59]:
data1 = [6,5,7,1,8]

In [60]:
type(data1)

list

In [61]:
arr1 = np.array(data1)

In [62]:
type(arr1)

numpy.ndarray

In [63]:
arr1.shape

(5,)

In [64]:
data2 = [[1,2,3,4],[2,3,4,5]]

In [65]:
arr2 = np.array(data2)

In [66]:
type(arr2)

numpy.ndarray

In [67]:
arr2.shape

(2, 4)

In [68]:
arr2.ndim

2

In [69]:
arr1.ndim

1

In [70]:
np.array([[[1,2],[3,4]],[[5,6],[7,8]]]).ndim

3

# ndarray 생성하기

In [71]:
np.zeros(10) # 메모리를 초기화 하고 0으로 값을 채워 넣는다.

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [72]:
np.empty(10) # zeros 비슷하지만, 메모리를 초기화 하지 않고 메모리값을 반환한다.

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [73]:
np.empty(30)

array([1.06823549e-311, 9.58487353e-322, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 1.16097020e-028, 1.48339293e-076, 1.48308606e-071,
       6.01033460e-067, 5.01163173e+217, 8.37170074e-144, 8.37821492e+169,
       4.99028117e+174, 7.11938412e-091, 1.59853677e+160, 5.01163188e+217,
       5.49419094e-143, 9.80058441e+252, 7.50189709e+247, 1.35617292e+248,
       4.49831115e-037, 1.29130412e+160, 4.04186736e-037, 2.67452389e+184,
       5.15059328e-062, 5.04621361e+180, 8.37170571e-144, 9.30350598e+199,
       5.60230216e-067, 5.90411176e+294])

In [20]:
np.ones((3,4)) #메모리를 초기화 하고 1로 채워 넣는다.

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [75]:
np.full((3,4),10)

array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]])

In [25]:
# ndarray 는 권장사항 아님
np.ndarray((3,))

array([1.33511018e-306, 1.33511969e-306, 6.23037996e-307])

# https://c11.kr/myoh-20100701

In [28]:
type(np.ones((3,4))[0][0])

numpy.float64

In [82]:
type(np.full((3,4),10)[0][0])

numpy.int32

In [85]:
type(4/2)

float

In [30]:
4*2.5

int

# index, slice
- 리스트와 동일
- 시퀀셜(Sequential) 데이터 이기 때문에 인덱싱과 슬라이싱이 가능하다.

In [90]:
arr_1 = np.arange(10)

In [92]:
arr_1[5]

5

In [95]:
arr_1[0]

0

In [96]:
arr_1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [94]:
arr_1[0:-1]

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [97]:
arr_1[0] = 10

In [98]:
arr_1

array([10,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [99]:
arr_1[5:-1] = 0

In [100]:
arr_1

array([10,  1,  2,  3,  4,  0,  0,  0,  0,  9])

In [101]:
arr2d_1= np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9]])

In [105]:
arr2d_1[2]

array([7, 8, 9])

In [106]:
arr2d_1[2][2]

9

In [112]:
arr2d_1[0:3]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [114]:
arr2d_1[:][1]

array([4, 5, 6])

In [117]:
arr2d_1[:,1]

array([2, 5, 8])

In [121]:
arr2d_2 = np.array([
    [[1,2,3,4],[5,6,7,8],[9,10,11,12]],
    [[13,14,15,16],[17,18,19,20],[21,22,23,24]]
])

In [122]:
arr2d_2.shape

(2, 3, 4)

In [123]:
arr2d_2[:,[1],[2]]

array([[ 7],
       [19]])

# 블리언 값


In [124]:
names = np.array(["오민엽", "조상우","오정석","정세영"])

In [125]:
names == '오민엽'

array([ True, False, False, False])

In [126]:
names != '오민엽'

array([False,  True,  True,  True])

In [127]:
names[names != '오민엽']

array(['조상우', '오정석', '정세영'], dtype='<U3')

In [128]:
data = np.random.randn(7,4)

In [129]:
data

array([[-0.86464617, -0.97687429,  0.4677455 , -1.11710622],
       [-1.05152894, -0.7337487 ,  0.12119663, -0.27564863],
       [ 0.24661762,  0.75266912,  0.41781214,  0.57523455],
       [ 1.01347698,  1.20123116,  0.27038419, -0.35396996],
       [-0.48653135, -0.04852031,  0.2872791 ,  0.40947229],
       [ 0.60802533,  0.24272869, -0.98671734,  0.53159843],
       [-1.36248835,  1.61764345,  2.38541021, -0.27471576]])

In [130]:
data<0

array([[ True,  True, False,  True],
       [ True,  True, False,  True],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True, False, False],
       [False, False,  True, False],
       [ True, False, False,  True]])

In [131]:
data[data<0]

array([-0.86464617, -0.97687429, -1.11710622, -1.05152894, -0.7337487 ,
       -0.27564863, -0.35396996, -0.48653135, -0.04852031, -0.98671734,
       -1.36248835, -0.27471576])

In [132]:
data[data>0]

array([0.4677455 , 0.12119663, 0.24661762, 0.75266912, 0.41781214,
       0.57523455, 1.01347698, 1.20123116, 0.27038419, 0.2872791 ,
       0.40947229, 0.60802533, 0.24272869, 0.53159843, 1.61764345,
       2.38541021])

In [133]:
data[data<0] = -1

In [139]:
data

array([[-1.        , -1.        ,  0.4677455 , -1.        ],
       [-1.        , -1.        ,  0.12119663, -1.        ],
       [ 0.24661762,  0.75266912,  0.41781214,  0.57523455],
       [ 1.01347698,  1.20123116,  0.27038419, -1.        ],
       [-1.        , -1.        ,  0.2872791 ,  0.40947229],
       [ 0.60802533,  0.24272869, -1.        ,  0.53159843],
       [-1.        ,  1.61764345,  2.38541021, -1.        ]])

# 팬시 색인
- 정수 배열 색인

In [141]:
arr = np.empty((8,4))

In [143]:
for i in range(8):
    arr[i] = i

In [145]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

- 특정한 row(행)

In [147]:
arr[[4,3,0]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.]])

In [149]:
arr[[-1,-2,-3]]

array([[7., 7., 7., 7.],
       [6., 6., 6., 6.],
       [5., 5., 5., 5.]])

In [160]:
arr2 = np.arange(32).reshape((8,4))

In [161]:
arr2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [165]:
arr2[[1,0],[0,2]]

array([4, 2])

In [174]:
arr2[[1,0]][:]# : 를 내부에 넣는건 x

array([[4, 5, 6, 7],
       [0, 1, 2, 3]])

In [135]:
arr2d_1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [138]:
arr2d_1[[0,1,2],[1,2,2]]

array([2, 6, 9])

# 벡터화 연산
- 배열에 함수를 적용하고 싶다.
- 함수를 벡터화 시킨다. -> 적용시킨다. (for 문을 구현 성능이 안좋다.)
- 브로드 캐스팅을 이용해 연산한다.

In [175]:
mat_1 = np.array(range(1,10)).reshape(3,3)

In [176]:
mat_1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [177]:
add_20  = lambda i: i + 20

In [178]:
vec_add_20 = np.vectorize(add_20)

In [179]:
vec_add_20(mat_1)

array([[21, 22, 23],
       [24, 25, 26],
       [27, 28, 29]])

In [180]:
mat_1 + 10

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

# 전치
    - 행렬의 행과 열을 변경해 준다.

In [185]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [184]:
arr.T

array([[0., 1., 2., 3., 4., 5., 6., 7.],
       [0., 1., 2., 3., 4., 5., 6., 7.],
       [0., 1., 2., 3., 4., 5., 6., 7.],
       [0., 1., 2., 3., 4., 5., 6., 7.]])

In [186]:
arr.transpose()

array([[0., 1., 2., 3., 4., 5., 6., 7.],
       [0., 1., 2., 3., 4., 5., 6., 7.],
       [0., 1., 2., 3., 4., 5., 6., 7.],
       [0., 1., 2., 3., 4., 5., 6., 7.]])

In [187]:
np.array([1,2,3,4,5]).T

array([1, 2, 3, 4, 5])

In [188]:
np.array([[1,2,3,4,5]]).T

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [190]:
vol2=np.array(range(30)).reshape((2,3,5))

In [191]:
vol2.T

array([[[ 0, 15],
        [ 5, 20],
        [10, 25]],

       [[ 1, 16],
        [ 6, 21],
        [11, 26]],

       [[ 2, 17],
        [ 7, 22],
        [12, 27]],

       [[ 3, 18],
        [ 8, 23],
        [13, 28]],

       [[ 4, 19],
        [ 9, 24],
        [14, 29]]])

- 행렬 덧셈,뺄,곱
- 전치행렬
- 방정식 -> 행렬 변경

# 유니버설 함수
- 데이터 원소별로 연산을 수행
    - 단항 유니버설 : exp, sqrt
    - 이항 : maxi, mini, add

In [195]:
arr = np.array([1,4,9,16])

In [196]:
np.sqrt(arr)

array([1., 2., 3., 4.])

In [197]:
np.exp(arr)

array([2.71828183e+00, 5.45981500e+01, 8.10308393e+03, 8.88611052e+06])

In [34]:
x = np.random.rand(8)
x

array([0.02391   , 0.17122905, 0.02791688, 0.19127988, 0.51568934,
       0.06029349, 0.29430553, 0.46831215])

In [35]:
y= np.random.rand(8)
y

array([0.80265415, 0.75091168, 0.72222606, 0.42088599, 0.57201643,
       0.13325963, 0.38449153, 0.20272113])

In [36]:
z= np.random.rand(8)

In [38]:
np.maximum(x,y)

array([0.80265415, 0.75091168, 0.72222606, 0.42088599, 0.57201643,
       0.13325963, 0.38449153, 0.46831215])

In [215]:
z

array([0.68248166, 0.07706489, 0.08230257, 0.26609981, 0.18606085,
       0.25744735, 0.46881679, 0.35076503])

In [214]:
np.minimum(x,y,z)

array([0.68248166, 0.07706489, 0.08230257, 0.26609981, 0.18606085,
       0.25744735, 0.46881679, 0.35076503])

In [209]:
np.add(x,y)

array([1.5170779 , 0.80448662, 0.37085352, 0.77041216, 0.82216519,
       1.02642691, 1.0924952 , 1.28568459])

In [210]:
x+y

array([1.5170779 , 0.80448662, 0.37085352, 0.77041216, 0.82216519,
       1.02642691, 1.0924952 , 1.28568459])

In [216]:
np.minimum(x,y,arr)

UFuncTypeError: Cannot cast ufunc 'minimum' output from dtype('float64') to dtype('int32') with casting rule 'same_kind'

In [219]:
f = np.random.rand(10)

In [220]:
np.maximum(x,y,f)

ValueError: operands could not be broadcast together with shapes (8,) (8,) (10,) 

- 메서드
    - 합, 평균, 표준편차
    - sum
    - mean
    - std,var
    - min, max

In [234]:
arr= np.random.rand(10)

In [235]:
arr

array([0.93846671, 0.00669761, 0.36139371, 0.70142202, 0.70941725,
       0.38658425, 0.06846981, 0.68083499, 0.52414925, 0.39766584])

In [236]:
arr.mean()

0.47751014489299576

In [237]:
np.mean(arr)

0.47751014489299576

In [239]:
np.sum(arr)

4.7751014489299575

In [241]:
arr.sum()

4.7751014489299575

In [250]:
arr= np.random.rand(10,5)

In [245]:
arr.sum()

24.504294686473727

In [247]:
arr

array([[0.75733194, 0.55961268, 0.79900256, 0.88360446, 0.33999292],
       [0.15358012, 0.21960043, 0.35724695, 0.03067401, 0.39430255],
       [0.10576078, 0.32645364, 0.08000438, 0.6859718 , 0.76746577],
       [0.7944953 , 0.83885022, 0.46228515, 0.88375547, 0.58463471],
       [0.58301622, 0.26339298, 0.49403731, 0.71785472, 0.11280676],
       [0.62846892, 0.35904245, 0.41405241, 0.25894341, 0.60692746],
       [0.51492093, 0.36030217, 0.52179099, 0.84946737, 0.60056631],
       [0.17123647, 0.64442687, 0.80559046, 0.48933369, 0.98407237],
       [0.37255846, 0.07297395, 0.72829745, 0.7235362 , 0.05270321],
       [0.29840805, 0.27304816, 0.65485022, 0.55930935, 0.36373353]])

In [246]:
arr.sum(axis=0)

array([4.37977718, 3.91770354, 5.31715788, 6.08245048, 4.8072056 ])

In [248]:
arr.sum(axis=1)

array([3.33954457, 1.15540405, 1.96565636, 3.56402085, 2.17110799,
       2.26743465, 2.84704777, 3.09465986, 1.95006928, 2.14934931])

In [252]:
np.sort(arr) # arr.sort()

array([[0.01560365, 0.07506817, 0.11387828, 0.51985965, 0.58349647],
       [0.1556045 , 0.44617325, 0.5226492 , 0.61241768, 0.62409766],
       [0.13067547, 0.15675434, 0.2651447 , 0.90504796, 0.9109415 ],
       [0.57277762, 0.58362821, 0.59349372, 0.70207736, 0.94950208],
       [0.37925205, 0.7544855 , 0.79573263, 0.83578828, 0.94472731],
       [0.00493109, 0.02207832, 0.183718  , 0.75136821, 0.81152562],
       [0.01672657, 0.08963956, 0.14422528, 0.15459377, 0.87653561],
       [0.12526062, 0.16106085, 0.18363688, 0.44559515, 0.67690566],
       [0.08073142, 0.20659362, 0.21596298, 0.42263735, 0.55872972],
       [0.06822686, 0.32182733, 0.49568447, 0.70626162, 0.83210941]])

# 선형대수 연산

In [254]:
x = np.array([[1,2,3],
            [4,5,6]])

In [255]:
y = np.array([[6,20],[7,21],[8,22]])

In [256]:
np.dot(x,y)

array([[ 44, 128],
       [107, 317]])

In [257]:
x @ y

array([[ 44, 128],
       [107, 317]])

In [259]:
w = np.array([[2,3],[5,6]])

In [260]:
y = np.array([[4],[5]])

In [261]:
w_1 = np.linalg.inv(w)

In [262]:
np.dot(w_1,y)

array([[-3.        ],
       [ 3.33333333]])

# linalg 모듈
- 선형대수에 필요한 역행렬과 행렬식에 관한 함수를포함하고 있다.
    - det : 행렬식을 계산
    - inv : 역행렬 (정사각 행렬만 가능)
    - ---------------------------
    - eig : 고윳값 고유벡터 계산
    - qr : qr분해 계산
    - svd : 특잇값 분해 계산
    - matrix_rank : 행렬 의 rank를 반환한다.
    
    

In [264]:
np.linalg.solve(w,y)

array([[-3.        ],
       [ 3.33333333]])

In [268]:
np.linalg.matrix_rank(w) # 독립차원의 차수

2

In [267]:
np.ndim(w) #실제 차원은 아니다. tensor기준의 차원

2