# XOR 신경망 구현

In [1]:
from tensorflow.compat.v1 import ConfigProto, InteractiveSession
config = ConfigProto()
config.gpu_options.per_process_gpu_memory_fraction = 0.3
session = InteractiveSession(config=config)

In [2]:
import tensorflow as tf
from tensorflow import keras
import numpy as np

In [6]:
x_data = [[0, 0],
         [0, 1],
         [1, 0],
         [1, 1]]
y_data = [[0],
         [1],
         [1],
         [0]]

In [7]:
x_data = np.array(x_data)
y_data = np.array(y_data)

In [45]:
x_data.shape

(4, 2)

In [46]:
model = keras.Sequential()

In [47]:
model.add(keras.layers.Dense(4, activation='tanh', input_shape=(2,)))
model.add(keras.layers.Dense(2, activation='tanh'))
model.add(keras.layers.Dense(1, activation='tanh'))

In [48]:
model.compile(optimizer='SGD', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [49]:
model.summary()

Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_17 (Dense)             (None, 4)                 12        
_________________________________________________________________
dense_18 (Dense)             (None, 2)                 10        
_________________________________________________________________
dense_19 (Dense)             (None, 1)                 3         
Total params: 25
Trainable params: 25
Non-trainable params: 0
_________________________________________________________________


In [50]:
model.fit(x_data, y_data, batch_size=4, epochs=2000)

Epoch 1/2000
1/1 [==============================] - 0s 997us/step - loss: 1.5082 - accuracy: 0.5000
Epoch 2/2000
1/1 [==============================] - 0s 997us/step - loss: 0.6890 - accuracy: 0.5000
Epoch 3/2000
1/1 [==============================] - 0s 996us/step - loss: 0.6887 - accuracy: 0.5000
Epoch 4/2000
1/1 [==============================] - 0s 998us/step - loss: 0.6883 - accuracy: 0.5000
Epoch 5/2000
1/1 [==============================] - 0s 0s/step - loss: 0.6879 - accuracy: 0.5000
Epoch 6/2000
1/1 [==============================] - 0s 996us/step - loss: 0.6876 - accuracy: 0.5000
Epoch 7/2000
1/1 [==============================] - 0s 996us/step - loss: 0.6872 - accuracy: 0.5000
Epoch 8/2000
1/1 [==============================] - 0s 997us/step - loss: 0.6868 - accuracy: 0.5000
Epoch 9/2000
1/1 [==============================] - 0s 997us/step - loss: 0.6865 - accuracy: 0.5000
Epoch 10/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.6861 - accuracy: 0.5000
Epoc

In [51]:
model.predict(x_data)

array([[-0.00303938],
       [ 0.9644018 ],
       [ 0.96515226],
       [-0.00415838]], dtype=float32)

In [52]:
np.round(model.predict(x_data))

array([[-0.],
       [ 1.],
       [ 1.],
       [-0.]], dtype=float32)

# Mnist 를 학습시켜 보자.

In [3]:
import tensorflow as tf
from tensorflow import keras
import numpy as np
import matplotlib.pyplot as plt
from tensorflow.keras.datasets import mnist

In [5]:
(X_train, y_train), (X_test, y_test) = mnist.load_data()

In [6]:
X_train.shape

(60000, 28, 28)

In [7]:
# 학습을 위해 data shape 을 변경. 연산을 위해 float 32 로 변경
X_train = X_train.reshape(60000, 784)
X_test = X_test.reshape(10000, 784)
X_train = X_train.astype('float32')
X_test = X_test.astype('float32')

In [8]:
y_train[0]

5

In [9]:
# one-hot encoding을 통해 target label의 값을 확률로 변경
Y_train = keras.utils.to_categorical(y_train)
Y_test = keras.utils.to_categorical(y_test)

In [10]:
# 정답이 5인 경우
Y_train[0]

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.], dtype=float32)

In [66]:
X_train.shape

(60000, 784)

In [67]:
X_train[0]

array([  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   

In [25]:
# model 생성
input_shape = (784, )

In [26]:
model = keras.Sequential()
model.add(keras.layers.Dense(128, activation = 'sigmoid', input_shape=(784,)))

In [27]:
model.add(keras.layers.Dense(128, activation = 'sigmoid'))
model.add(keras.layers.Dense(10, activation ='softmax'))

In [28]:
model.compile(optimizer='SGD', loss='categorical_crossentropy', metrics=['accuracy'])

In [29]:
# 학습이 오래걸릴수도 있으니 epochs 는 처음에는 작게 1 회 또는 2회 정도. -> 빠르면 성능을 높이기 위해 20회
model.fit(X_train, Y_train, batch_size=128, epochs=50)

Epoch 1/50
469/469 [==============================] - 1s 1ms/step - loss: 1.9394 - accuracy: 0.5651
Epoch 2/50
469/469 [==============================] - 1s 1ms/step - loss: 1.3404 - accuracy: 0.7769
Epoch 3/50
469/469 [==============================] - 1s 1ms/step - loss: 0.9483 - accuracy: 0.8309
Epoch 4/50
469/469 [==============================] - 1s 1ms/step - loss: 0.7245 - accuracy: 0.8608
Epoch 5/50
469/469 [==============================] - 1s 1ms/step - loss: 0.5899 - accuracy: 0.8787
Epoch 6/50
469/469 [==============================] - 1s 1ms/step - loss: 0.5028 - accuracy: 0.8899
Epoch 7/50
469/469 [==============================] - 1s 1ms/step - loss: 0.4442 - accuracy: 0.8981
Epoch 8/50
469/469 [==============================] - 1s 1ms/step - loss: 0.4018 - accuracy: 0.9050
Epoch 9/50
469/469 [==============================] - 1s 1ms/step - loss: 0.3703 - accuracy: 0.9101
Epoch 10/50
469/469 [==============================] - 1s 1ms/step - loss: 0.3460 - accuracy: 0.9136

In [79]:
type((784))

int

In [82]:
type((784, ))

tuple

In [31]:
model_2 = keras.Sequential()
model_2.add(keras.layers.Dense(512, activation = 'relu', input_shape=(784,)))
model_2.add(keras.layers.Dense(512, activation = 'relu'))
model_2.add(keras.layers.Dense(10, activation = 'softmax'))

In [38]:
model_2.compile(optimizer='adam', loss= 'categorical_crossentropy', metrics = ['accuracy'])

In [39]:
model_2.fit(X_train, Y_train, batch_size=128, epochs=5)

Epoch 1/5
469/469 [==============================] - 1s 1ms/step - loss: 2.2921 - accuracy: 0.9065
Epoch 2/5
469/469 [==============================] - 1s 1ms/step - loss: 0.2612 - accuracy: 0.9572
Epoch 3/5
469/469 [==============================] - 1s 1ms/step - loss: 0.1570 - accuracy: 0.9697
Epoch 4/5
469/469 [==============================] - 1s 1ms/step - loss: 0.1376 - accuracy: 0.9726
Epoch 5/5
469/469 [==============================] - 1s 1ms/step - loss: 0.1147 - accuracy: 0.9765
